# Generated by Django 6.0.3 on 2026-03-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='tag',
            new_name='tags',
        ),
    ]
