# Generated by Django 6.0.3 on 2026-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('createt_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
